### ISSUE TITLE
关于这几个项目的一些问题

### ISSUE THREAD

**Issue by KakaruHayate** [PlayVoice/max-vc#1]
非dl方向，仅语音合成技术玩家，因为这几个项目采用了与其他svc项目encoder——hubert不同的whisper比较感兴趣。
1.我发现max-vc主要改进的是f0的提取问题（使用了torchcrepe），按照描述是否可以把这个项目归并到lora-svc？实际上现在几个流行的svc项目也都适配了torchcrepe
2.我看了下“so-vits-svc-5.0”的config，这个以后也是要训练16kHz的模型吗？我觉得16kHz本身低采样率造成的失真可能相比更高的采样率造成的损失更加大一些。

**Comment by MaxMax2016** [comment]
这里的crepe和其他项目完全不一样，这里的crepe和hubert比较类似。因为没有真的提取f0，用不了nsf，效果无法和用nsf的上限效果比。16k的问题，是因为这里主要关注于模型和算法本身，当然算力也是个重要影响因素。

**Comment by KakaruHayate** [comment]
> 这里的crepe和其他项目完全不一样，这里的crepe和hubert比较类似。因为没有真的提取f0，用不了nsf，效果无法和用nsf的上限效果比。16k的问题，是因为这里主要关注于模型和算法本身，当然算力也是个重要影响因素。

那么今后会有更高采样率的版本使用吗？例如sovits5.0

**Comment by MaxMax2016** [comment]
可能会做，但是会比较久
